project:
  type: website
  resources:
    - "images/opengraph.png"
    - "data"
    - "ethics"
  render:
    - "*.qmd"
    - "!README.qmd"

website:
  page-navigation: true
  title: "Forecast combinations"
  description: "Homepage for the forecast combinations workshop at ISF 2026"
  site-url: "https://workshop.nectric.com.au/isf2026"

  repo-url: https://github.com/mitchelloharawild/workshop-isf2026
  repo-actions: [edit, issue]

  # opengraph: true
  twitter-card:
    creator: "@mitchoharawild"
  image: "/images/opengraph.png"

  favicon: "/images/fable.svg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2026, Mitchell O'Hara-Wild"
    background: "#426D98"

  navbar:
    background: "#426D98"
    pinned: true
    align: center
    left:
    - text: Slides
      menu:
        - text: Decomposition forecasting
          href: slides/decomposition/
        - text: Ensembles and reconciliation
          href: slides/combination/
    # - text: Feedback
    #   href: https://feedback.nectric.com.au/w0rw
    # - text: Exercises
    #   href: exercises.qmd
    right:
      - icon: download
        text: Downloads
        menu:
          - text: Everything
            href: 'https://github.com/mitchelloharawild/workshop-isf2026/archive/refs/heads/main.zip'
          # - text: Slides
            # href: 'slides.zip'
          - text: Lab sessions
            href: 'labs.zip'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/mitchelloharawild/workshop-isf2026

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Open Sans"
    include-after-body: plausible.html
